org: natebessa
app: soccer-rsvp
service: soccer-rsvp

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app.app
    pythonBin: python3

provider:
  name: aws
  runtime: python3.7
  timeout: 25 # default of 6 seconds is too short to send SMS to whole roster

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
    timeout: 25 # default of 6 seconds is too short to send SMS to whole roster

plugins:
  - serverless-wsgi
  - serverless-python-requirements
