org: natebessa
app: soccer-rsvp
service: soccer-rsvp

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app
    pythonBin: python3

provider:
  name: aws
  runtime: python3.7

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
